[workspace]
resolver = "2"
members = ["crates/cpu-power-hal", "crates/power-agent", "crates/pstate-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/aarnaud/k8s-power-management"

[profile.release]
lto = true
strip = true
codegen-units = 1
